# Generated by Django 4.1.7 on 2023-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['id', 'content'], 'verbose_name': 'Текст', 'verbose_name_plural': 'Тексти'},
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='text',
            name='most_used_word',
            field=models.CharField(max_length=25, verbose_name='Найчастіше використовуване слово'),
        ),
        migrations.AlterField(
            model_name='text',
            name='sentence_number',
            field=models.IntegerField(verbose_name='Кількість речень'),
        ),
        migrations.AlterField(
            model_name='text',
            name='symbol_number',
            field=models.IntegerField(verbose_name='Кількість символів'),
        ),
        migrations.AlterField(
            model_name='text',
            name='word_number',
            field=models.IntegerField(verbose_name='Кількість слів'),
        ),
    ]
